#! /bin/bash
set -eu

# Source app helpers
. /usr/share/yunohost/helpers

# This is a single instance app
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
is_public=$YNH_APP_ARG_IS_PUBLIC
git_project_root=$YNH_APP_ARG_GIT_PROJECT_ROOT

final_path=/var/www/$app

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
|| ynh_die "Path not available: ${domain}${path_url}"

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
	echo "Error : the chosen admin user does not exist"
	ynh_die 1
fi

# Check /var/www/$app path is available
if [ -f $final_path ]; then
	echo "This path already contains a folder"
	ynh_die 1
fi

# Check directories 
[[ -d $final_path ]] && ynh_die \
"The destination directory '$final_path' already exists.\
 You should safely delete it before installing this app."
[[ ! -d $git_project_root ]] && ynh_die \
"The git project root directory '$git_project_root' doesn't exist.\
 You should safely create it/choose another before installing this app."

# Check user parameter
ynh_user_exists "$admin" \
  || ynh_die "The chosen admin user does not exist."

# Save app settings
ynh_app_setting_set $app admin "$admin"
ynh_app_setting_set $app is_public "$is_public"
ynh_app_setting_set $app final_path "$final_path"

# Installing packages
echo "Updating apt package db..."
sudo apt-get -qq update
echo "Installing dependancies ..."
sudo apt-get install -qqy fcgiwrap gitweb >/dev/null 2>&1

# Adding user www-data to group git
sudo adduser www-data git 

sudo cp ../conf/gitweb.conf /etc/gitweb.conf
sudo chown root:root /etc/gitweb.conf 
sudo chmod 644 /etc/gitweb.conf

sudo ln -s /usr/share/gitweb $final_path
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@YNH_WWW_PATH@$path_url@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@YNH_APP_PATH@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@YNH_GIT_PROJECT_ROOT@$git_project_root@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo chown root: /etc/nginx/conf.d/$domain.d/$app.conf
sudo chmod 600 /etc/nginx/conf.d/$domain.d/$app.conf

sudo yunohost app addaccess --users="$admin" $app

# If app is public, add url to SSOWat conf as skipped_uris
if [[ $is_public -eq 1 ]]; then
  # unprotected_uris allows SSO credentials to be passed anyway.
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

sudo service nginx reload
sudo yunohost app ssowatconf
