#! /bin/bash

app=gitweb

domain=$1
path=$2
admin=$3
is_public=$4
final_path=/var/www$path

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
	echo "Path of the domain is not available"
	exit 1
fi

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
	echo "Error : the chosen admin user does not exist"
	exit 1
fi

# Check /var/www/$app path is available
if [ -f $final_path ]; then
	echo "This path already contains a folder"
	exit 1
fi

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app is_public -v "$is_public"
sudo yunohost app setting $app final_path -v "$final_path"

echo "Updating apt ..."
sudo apt-get -qq update
echo "Installing dependancies ..."
sudo apt-get install -qqy fcgiwrap gitweb >/dev/null 2>&1

sudo adduser www-data git 

sudo cp ../conf/gitweb.conf /etc/gitweb.conf
sudo chown root:root /etc/gitweb.conf 
sudo chmod 644 /etc/gitweb.conf

sudo ln -s /usr/share/gitweb $final_path
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s,YNH_NGINX_PATH,$path,g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo chown root: /etc/nginx/conf.d/$domain.d/$app.conf
sudo chmod 600 /etc/nginx/conf.d/$domain.d/$app.conf


sudo yunohost app addaccess $app -u $admin

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
	sudo yunohost app setting $app skipped_uris -v "/"
fi

sudo service nginx restart
sudo yunohost app ssowatconf