#! /bin/bash
set -u

# Source app helpers
. /usr/share/yunohost/helpers

app=gitweb

domain=$(ynh_app_setting_set $app domain)
final_path=$(ynh_app_setting_set $app final_path)
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -rf $final_path
sudo deluser www-data git
